# /webapps/erd-ecosystem/devops/k8s/overlays/local/patch-imagepullpolicy-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmbok-frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: pmbok-frontend
          imagePullPolicy: IfNotPresent
