apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pmbok-ingress
spec:
  rules:
    - host: pmbok.localhost
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: local-pmbok-backend-service
                port:
                  number: 8000
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: local-pmbok-backend-service
                port:
                  number: 8000
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: local-pmbok-backend-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: local-pmbok-frontend-service
                port:
                  number: 80
    - host: api.pmbok.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: local-pmbok-backend-service
                port:
                  number: 8000
