# docker-compose.staging-http.yml
services:
  backend-staging:
    # Exponemos el backend por HTTP en el host
    ports:
      - "8000:8000"

  frontend-staging:
    # (Opcional, pero útil) asegúrate de que el backend esté arriba cuando levantes ambos
    depends_on:
      backend-staging:
        condition: service_started
    # Servimos el build por HTTP en 8080
    ports:
      - "8080:80"
