# docker-compose.dev-http.yml
services:
  backend-dev:
    environment:
      DJANGO_DEBUG: "True"
      # Si algún día habilitas un flag en settings.py para forzar redirección SSL,
      # puedes desactivarlo aquí (solo si lo implementas):
      # ENABLE_SSL_REDIRECT: "0"

  frontend-dev:
    environment:
      # Asegura que el frontend apunte al backend interno por HTTP en dev
      VITE_API_URL: http://backend-dev:8000/api
      # (opcional) si quieres obligar a Vite a escuchar en 0.0.0.0:
      # VITE_HOST: 0.0.0.0
