# /webapps/erd-ecosystem/devops/k8s/components/postgres-db/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - pv.yaml
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  # Herramientas opcionales
  - pgadmin-secret.yaml
  - pgadmin-deployment.yaml
  - pgadmin-service.yaml