# /webapps/erd-ecosystem/devops/k8s/components/postgres-db/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres
type: Opaque
stringData:
  # Variables para la Base de Datos (Postgres Image)
  POSTGRES_DB: pmbok_db
  POSTGRES_USER: pmbok_user
  POSTGRES_PASSWORD: secretpassword
  
  # Variables ESPEJO para el Backend (Django)
  # Al ponerlas aqu√≠, evitamos escribirlas a mano en el patch del overlay
  DB_NAME: pmbok_db
  DB_USER: pmbok_user
  DB_PASSWORD: secretpassword