apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pmbok-backend-deployment.yaml
  - pmbok-backend-service.yaml
  - pmbok-frontend-deployment.yaml
  - pmbok-frontend-service.yaml
  - ingress.yaml