# /webapps/erd-ecosystem/devops/k8s/base/pmbok/pmbok-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmbok-backend-deployment
  labels:
    app: pmbok-backend
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pmbok-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: pmbok-backend
    spec:
      containers:
        - name: pmbok-backend
          image: ghcr.io/elrincondeldetective/pmbok/backend:sha-8415d5f
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            # ConfiguraciÃ³n de ConexiÃ³n a BD
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DJANGO_DEBUG
              value: "0"
            # ðŸ‘‡ FIX 1: Desactivar SSL para conexiÃ³n interna
            - name: DB_SSLMODE
              value: "disable"
            # ðŸ‘‡ FIX 2: Permitir IPs de K8s para Health Checks
            - name: EXTRA_ALLOWED_HOSTS
              value: "*"
