# /webapps/erd-ecosystem/devops/k8s/base/pmbok/pmbok-frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pmbok-frontend-service
  labels:
    app: pmbok-frontend
spec:
  # üëá CAMBIO CLAVE: Usamos ClusterIP para que solo el Ingress pueda contactarlo.
  type: ClusterIP
  selector:
    app: pmbok-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      # ‚ùå Eliminamos nodePort: 30100 (Ya no se necesita)