# apps/pmbok/.github/workflows/test.yaml
name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/test.yaml"
      - ".github/actions/**"
  pull_request:

jobs:
  # 1. Detectar cambios
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/utils/file-filters.yaml

  # 2. Ejecutar Tests
  test:
    needs: filter
    if: ${{ needs.filter.outputs.services != '[]' }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: pmbok_test_db
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Usamos la acci√≥n compuesta que acabamos de crear
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          working-directory: ${{ matrix.service }}

      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: task install-ci

      - name: Run tests
        working-directory: ${{ matrix.service }}
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_NAME: pmbok_test_db
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_SSLMODE: disable
        run: task test